index:
  path: /accueil
  controller: App\Controller\AccueilController::accueil
login_check:
  path: /login_check
  methods: POST
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST